# render.yaml
services:
  - name: shiza-will-smith-proxy
    type: web
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    # (Optional) Set plan, region, environment variables, etc.
    plan: free        # e.g. use "free", "starter", "standard", ...
    # region: oregon
    envVars:
      - key: PORT
        value: "3000"
